<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;
use think\Session;

class Admin extends Controller
{
    protected $admin_id;
    protected $role_id;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        /** 检验并赋值给变量 */

        if (Session::has("admin_id")) {
            $this->admin_id=Session::get('admin_id');
            $this->role_id=Session::get('role_id');
        }else {
            return_msg(400,'请登录');
        }
    }
}