<?php

namespace app\agent\controller;

use app\agent\model\TotalAgent;
use think\Controller;
use think\Request;
use think\Session;

class Agent extends Controller
{
    protected $this_year;
    protected $time_limit;
    protected $register_time;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->this_year = strtotime(date("Y-01-01", time()));
        $id = Session::get("username_")["id"];
        if (!$id) {
            return_msg(400, "请登录");
        }
        $res = TotalAgent::get($id);
        $this->register_time = $res->getData()['create_time'];
        if ($this->this_year > $this->register_time) {
            $this->time_limit = $this->this_year;
        } else {
            $this->time_limit = $this->register_time;
        }
    }
}
